# Template Matching - OpenCV

In [2]:
import cv2
import numpy as np

In [24]:
scr_img = cv2.imread('./images/game.png', cv2.IMREAD_UNCHANGED)
wood_img = cv2.imread('./images/woodleft.png', cv2.IMREAD_UNCHANGED)
scr_img = scr_img[:, :, :3]
wood_img = wood_img[:, :, :3]

In [12]:
cv2.imshow('Farm', scr_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
cv2.imshow('Needle', wood_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Template Matching
<ul>
    <li>There are 6 comparison methods</li>
    <ul>
        <li>TM_CCOEFF</li>
        <li>TM_CCOEFF_NORMED</li>
        <li>TM_CCORR</li>
        <li>TM_CCORR_NORMED</li>
        <li>TM_SQDIFF</li>
        <li>TM_SQDIFF_NORMED</li>
    </ul>
    <li><a href="https://docs.opencv.org/master/d4/dc6/tutorial_py_template_matching.html">OpenCV Template Matching Docs</a></li>
</ul>

In [14]:
result = cv2.matchTemplate(scr_img, wood_img, cv2.TM_CCOEFF_NORMED)
result

array([[0.19677432, 0.19716825, 0.19754867, ..., 0.14988357, 0.14881957,
        0.15007152],
       [0.20088631, 0.20118506, 0.20147446, ..., 0.15543395, 0.15446486,
        0.15579143],
       [0.20378897, 0.20401122, 0.20423204, ..., 0.15999822, 0.15912724,
        0.16053498],
       ...,
       [0.1517121 , 0.15140192, 0.15107244, ..., 0.05114698, 0.0504929 ,
        0.05058278],
       [0.08262072, 0.0818767 , 0.08123602, ..., 0.02786314, 0.02773208,
        0.02832746],
       [0.01393982, 0.01264496, 0.01160971, ..., 0.00590401, 0.00633073,
        0.00747266]], dtype=float32)

In [15]:
cv2.imshow('Result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Get Max Result

In [16]:
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
max_loc

(76, 35)

In [17]:
max_val

1.0

### Paint Square on Main Image

In [18]:
w = wood_img.shape[1]
h = wood_img.shape[0]

In [19]:
cv2.rectangle(scr_img, max_loc, 
              (max_loc[0] + w, max_loc[1] + h), (0, 255, 255), 2)

array([[[160, 212, 232],
        [160, 212, 232],
        [159, 211, 230],
        ...,
        [  9,  37,  78],
        [ 16,  45,  87],
        [ 25,  57, 102]],

       [[159, 211, 231],
        [159, 211, 231],
        [158, 210, 229],
        ...,
        [  7,  34,  73],
        [ 14,  43,  85],
        [ 25,  57, 101]],

       [[158, 210, 229],
        [158, 210, 229],
        [156, 209, 228],
        ...,
        [  6,  34,  72],
        [ 14,  43,  84],
        [ 25,  57, 101]],

       ...,

       [[  0, 146, 155],
        [  0, 146, 155],
        [  0, 146, 155],
        ...,
        [  0,  83,  84],
        [  0,  83,  84],
        [  0,  83,  84]],

       [[  0, 146, 155],
        [  0, 146, 155],
        [  0, 146, 155],
        ...,
        [  0,  79,  82],
        [  0,  79,  82],
        [  0,  79,  82]],

       [[  0, 146, 155],
        [  0, 146, 155],
        [  0, 146, 155],
        ...,
        [  0,  77,  81],
        [  0,  77,  81],
        [  0,  77,  81]]

### Paint Multiple Squares

In [20]:
threshold = .85  # 阈值
yloc, xloc = np.where(result >= threshold)
len(xloc)

30

In [21]:
for (x, y) in zip(xloc, yloc):
    cv2.rectangle(scr_img, (x, y), (x + w, y + h), (0, 255, 255), 2)

In [22]:
cv2.imshow('Farm', scr_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
rectangles = []
for (x, y) in zip(xloc, yloc):
    rectangles.append([int(x), int(y), int(w), int(h)])
    rectangles.append([int(x), int(y), int(w), int(h)])
len(rectangles)

150

In [28]:
rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
rectangles

array([[731, 237,  66,  41],
       [603, 301,  66,  41],
       [731, 301,  66,  41],
       [539, 333,  66,  41],
       [603, 365,  66,  41]])

In [29]:
len(rectangles)

5