# Template Matching - OpenCV

In [1]:
import cv2
import numpy as np

In [2]:
farm_img = cv2.imread('./images/farm.png', cv2.IMREAD_UNCHANGED)
wheat_img = cv2.imread('./images/needle.png', cv2.IMREAD_UNCHANGED)

In [3]:
cv2.imshow('Farm', farm_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cv2.imshow('Needle', wheat_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Template Matching

## Template Matching
<ul>
    <li>There are 6 comparison methods</li>
    <ul>
        <li>TM_CCOEFF</li>
        <li>TM_CCOEFF_NORMED</li>
        <li>TM_CCORR</li>
        <li>TM_CCORR_NORMED</li>
        <li>TM_SQDIFF</li>
        <li>TM_SQDIFF_NORMED</li>
    </ul>
    <li><a href="https://docs.opencv.org/master/d4/dc6/tutorial_py_template_matching.html">OpenCV Template Matching Docs</a></li>
</ul>

In [13]:
result = cv2.matchTemplate(farm_img, wheat_img, cv2.TM_CCOEFF_NORMED)
result

array([[ 0.06750904,  0.04520004,  0.00044769, ...,  0.02551172,
        -0.00496834, -0.03841621],
       [ 0.05815947,  0.04590913,  0.00498679, ...,  0.02127783,
         0.01251658, -0.02776311],
       [ 0.0543881 ,  0.03879378,  0.01293975, ...,  0.03491033,
         0.01929776, -0.02135566],
       ...,
       [ 0.01017392,  0.00539028,  0.00406321, ..., -0.1651042 ,
        -0.1613754 , -0.15947627],
       [ 0.02842162,  0.01886271,  0.01513829, ..., -0.16116129,
        -0.16232157, -0.16182268],
       [ 0.02051085,  0.01673134,  0.00984759, ..., -0.15915021,
        -0.16096115, -0.15916666]], dtype=float32)

In [6]:
cv2.imshow('Result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Get Max Result

In [8]:
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
max_loc

(731, 301)

In [9]:
max_val

0.999998927116394

### Paint Square on Main Image

In [10]:
w = wheat_img.shape[1]
h = wheat_img.shape[0]

In [12]:
cv2.rectangle(farm_img, max_loc, 
              (max_loc[0] + w, max_loc[1] + h), (0, 255, 255), 2)

array([[[ 37, 114,  84],
        [ 55, 130, 102],
        [ 38, 110,  77],
        ...,
        [ 67, 111,  27],
        [ 67, 111,  27],
        [ 53, 111,  18]],

       [[ 36, 121,  78],
        [ 38, 110,  77],
        [ 38, 110,  77],
        ...,
        [ 67, 111,  27],
        [ 67, 111,  27],
        [ 67, 111,  27]],

       [[ 48, 165, 109],
        [ 50, 158,  96],
        [ 36, 121,  78],
        ...,
        [ 67, 111,  27],
        [ 67, 111,  27],
        [ 66, 124,  25]],

       ...,

       [[172,  93,  14],
        [172,  93,  14],
        [172,  93,  14],
        ...,
        [169, 214, 237],
        [171, 216, 239],
        [172, 217, 240]],

       [[173,  94,  15],
        [173,  94,  15],
        [172,  93,  14],
        ...,
        [172, 217, 240],
        [172, 217, 240],
        [173, 215, 239]],

       [[173,  94,  15],
        [173,  94,  15],
        [172,  93,  14],
        ...,
        [172, 214, 238],
        [173, 215, 239],
        [173, 215, 239]]

### Paint Multiple Squares

In [17]:
threshold = .60  # 阈值
yloc, xloc = np.where(result >= threshold)
len(xloc)

11

In [18]:
for (x, y) in zip(xloc, yloc):
    cv2.rectangle(farm_img, (x, y), (x + w, y + h), (0, 255, 255), 2)

In [19]:
cv2.imshow('Farm', farm_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
rectangles = []
for (x, y) in zip(xloc, yloc):
    rectangles.append([int(x), int(y), int(w), int(h)])
    rectangles.append([int(x), int(y), int(w), int(h)])
len(rectangles)

22

In [28]:
rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
rectangles

array([[731, 237,  66,  41],
       [603, 301,  66,  41],
       [731, 301,  66,  41],
       [539, 333,  66,  41],
       [603, 365,  66,  41]])

In [29]:
len(rectangles)

5